[general]
shuffle_caption = true
caption_extension = '.txt'
keep_tokens = 1

# This is a fine-tuning dataset
[[datasets]]
resolution = 512  #[512, 512]
batch_size = 4

#  [[datasets.subsets]]
#  image_dir = '/home/lev/project/ml-modern/homework/hw02/training/data/1_cartoon character'
#  metadata_file = '?????piyo_md.json'
#  # This subset uses keep_tokens = 1 (the value of [general])


